function [] = MYGUI()


S.fh = figure('units','pixels',...
              'position',[100 200 800 500],...
              'menubar','none',...
              'name','Automated Attendance System',...
              'numbertitle','off',...
              'resize','off');
S.pb = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[250 400 300 50],...
                 'string','Mark the Attendance',...
                 'callback',{@pb_call1},...
                 'backgroundc',[0.66 .94 .94],...
                 'busyaction','cancel',...
                 'interrupt','off');
S.pb = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[275 300 250 50],...
                 'string','Generate Attendance List',...
                 'callback',{@pb_call2},...
                 'backgroundc',[0.80 .96 .91],...
                 'busyaction','cancel',...
                 'interrupt','off');
S.pb = uicontrol('style','push',...
                 'unit','pix',...
                 'position',[300 200 200 50],...
                 'string','Send report to parents via mail',...
                 'callback',{@pb_call3},...
                 'backgroundc',[0.74 .84 .94],...
                 'busyaction','cancel',...
                 'interrupt','off');             
                          
                 
function [] = pb_call1(varargin)
% Callback for pushbutton.
h = varargin{1}; % Get the caller's handle.
col = get(h,'backg');  % Get the background color of the figure.
set(h,'str','Processing...','backg',[1 .6 .6]) % Change color of button. 

pause(.01)  % FLUSH the event queue, drawnow would work too.

demo();
A = rand(3000000,1);
A = sort(A); %#ok 
set(h,'str','Mark the Attendance','backg',col)  % Now reset the button features.
     
function [] = pb_call2(varargin)
% Callback for pushbutton.
h = varargin{1}; % Get the caller's handle.
col = get(h,'backg');  % Get the background color of the figure.
set(h,'str','Generating...','backg',[1 .6 .6]) % Change color of button. 

pause(.01)  % FLUSH the event queue, drawnow would work too.
exce();
A = rand(3000000,1);
A = sort(A); %#ok 
set(h,'str','Generate Attendance List','backg',col)  % Now reset the button features.


function [] = pb_call3(varargin)
% Callback for pushbutton.
h = varargin{1}; % Get the caller's handle.
col = get(h,'backg');  % Get the background color of the figure.
set(h,'str','Sending...','backg',[1 .6 .6]) % Change color of button. 

pause(.01)  % FLUSH the event queue, drawnow would work too.
mails();
A = rand(3000000,1);
A = sort(A); %#ok 
set(h,'str','Send report to parents via mail','backg',col)  % Now reset the button features.

